export const transactionsRowRecipes = {
  shell: [
    'relative rounded-md border-b border-slate-200/70 transition-[box-shadow,colors] duration-150 ease-out',
    'dark:border-slate-700/50',
    'hover:ring-2',
    'hover:ring-emerald-400/60',
    'dark:hover:ring-emerald-400/50',
  ],
  mainSurface: ['absolute', 'inset-0', 'z-0', 'rounded-md', 'bg-transparent'],
  mainSurfaceHost: ['relative', 'min-w-0', 'w-full'],
  mainSurfaceContent: ['relative', 'z-10', 'pointer-events-none'],
  mobileAmount: [
    'pointer-events-none',
    'absolute',
    'top-2.5',
    'right-3',
    'z-10',
    'shrink-0',
    'tabular-nums',
  ],
  mobileCategoryAnchor: ['absolute', 'bottom-2.5', 'right-3', 'z-20'],
  mobileMerchantLine: ['min-w-0', 'pr-28'],
  mobileMetaBlock: ['mt-1', 'min-w-0', 'pr-28'],
  placeholder: [
    'pointer-events-none',
    'select-none',
    'border-b',
    'border-slate-200/70',
    'dark:border-slate-700/50',
  ],
  placeholderDesktopHeight: ['h-[3.75rem]'],
  placeholderMobileHeight: ['min-h-[5.25rem]'],
  odd: [
    'bg-[color:color-mix(in_srgb,var(--color-surface-muted-chip)_40%,transparent)]',
    'dark:bg-slate-700/20',
  ],
  even: ['bg-transparent', 'dark:bg-transparent'],
  merchantEllipsis: ['min-w-0', 'overflow-hidden', 'text-ellipsis', 'whitespace-nowrap'],
  merchantCell: ['max-w-0', 'overflow-hidden', 'text-ellipsis', 'whitespace-nowrap'],
  categoryPill: [
    'w-full',
    'min-w-0',
    '!justify-end',
    '!gap-0',
    '!px-0',
    '!py-0',
    'hover:!translate-y-0',
  ],
  categoryFilterPill: ['px-2', 'py-0'],
  categoryLabel: ['min-w-0', 'flex-1', 'truncate', 'text-right'],
  categoryChevron: ['ml-1', 'shrink-0'],
} as const;
