import {
  brandNeutral,
  border as semanticBorders,
  effect as uiEffectRecipes,
  surface as uiSurfaceRecipes,
} from '@/ui/recipes';

export const transactionsRowRecipes = {
  shell: [
    'group relative w-full min-w-0 overflow-hidden rounded-md border-b transition-[box-shadow,colors] duration-150 ease-out',
    brandNeutral.borderSubtle,
    'hover:ring-2 hover:ring-inset hover:ring-[color:color-mix(in_srgb,var(--color-brand-teal)_60%,transparent)]',
    'dark:hover:ring-[color:color-mix(in_srgb,var(--color-brand-mint)_50%,transparent)]',
  ],
  mainSurfaceHost: ['relative', 'min-w-0', 'w-full'],
  mobileAmount: [
    'pointer-events-none',
    'absolute',
    'top-2.5',
    'right-3',
    'z-10',
    'shrink-0',
    'tabular-nums',
  ],
  mobileCategoryAnchor: [
    'absolute',
    'bottom-2.5',
    'right-3',
    'left-3',
    'z-20',
    'flex',
    'min-w-0',
    'items-center',
    'justify-end',
  ],
  mobileAmountPage: [
    'pointer-events-none',
    'absolute',
    'top-2.5',
    'right-4',
    'md:right-8',
    'lg:right-8',
    'z-10',
    'shrink-0',
    'tabular-nums',
  ],
  mobileCategoryAnchorPage: [
    'absolute',
    'bottom-2.5',
    'right-4',
    'md:right-8',
    'lg:right-8',
    'z-20',
    'w-fit',
    'max-w-full',
  ],
  mobileMerchantLine: ['min-w-0', 'pr-28'],
  mobileMetaBlock: ['mt-1', 'min-w-0', 'pr-28'],
  placeholder: ['pointer-events-none', 'select-none', 'border-b', brandNeutral.borderSubtle],
  placeholderDesktopHeight: ['h-[3.75rem]'],
  placeholderMobileHeight: ['min-h-[6rem]'],
  odd: [
    'bg-[color:color-mix(in_srgb,var(--color-brand-fog)_82%,transparent)]',
    'dark:bg-[color:color-mix(in_srgb,var(--color-brand-navy)_40%,transparent)]',
  ],
  even: ['bg-transparent', 'dark:bg-transparent'],
  merchantEllipsis: ['min-w-0', 'overflow-hidden', 'text-ellipsis', 'whitespace-nowrap'],
  merchantCell: ['min-w-0', 'overflow-hidden', 'text-ellipsis', 'whitespace-nowrap', 'text-left'],
  categoryPill: [
    'w-fit',
    'max-w-full',
    'min-w-0',
    '!justify-end',
    '!gap-0',
    '!px-0',
    '!py-0',
    '!overflow-visible',
    'hover:!translate-y-0',
  ],
  categoryFilterPill: ['px-2', 'py-0'],
  contextualFilterChipGlass: [
    ...uiEffectRecipes.glassBackdrop,
    'border',
    ...uiSurfaceRecipes.floatingChromePanel,
    ...semanticBorders.floatingChrome,
  ],
  contextualFilterChipGlassChrome: [
    ...uiEffectRecipes.glassBackdrop,
    'border',
    ...semanticBorders.floatingChrome,
  ],
  contextualFilterScroll: ['w-full', 'max-w-full', 'py-1.5'],
  selectedCategorySticky: ['sticky', 'z-10'],
  selectedCategoryStickyLeft: ['left-0'],
  selectedCategoryStickyRight: ['right-0'],
  selectedCategoryStickyLeftOffset: ['left-9', 'md:left-8', 'lg:left-7'],
  selectedCategoryStickyRightOffset: ['right-9', 'md:right-8', 'lg:right-7'],
  contextualFilterMaskViewport: ['min-w-0', 'w-full', 'max-w-full', 'overflow-hidden'],
  contextualFilterScrollArrow: [
    'absolute',
    'top-1/2',
    'z-20',
    '-translate-y-1/2',
    'hover:!-translate-y-1/2',
    'active:!-translate-y-1/2',
    'shrink-0',
  ],
  contextualFilterScrollArrowLeft: ['left-0'],
  contextualFilterScrollArrowRight: ['right-0'],
  categoryLabel: ['min-w-0', 'flex-1', 'truncate', 'text-right'],
  categoryLabelReadOnly: ['truncate', 'text-right'],
  categoryChevron: ['ml-1', 'shrink-0'],
  desktopGridCols:
    'grid-cols-[minmax(0,9rem)_minmax(0,1fr)_minmax(0,8rem)_minmax(0,12rem)_minmax(0,1fr)]',
  desktopGridRow: ['grid', 'w-full', 'items-center'],
  desktopGridHeader: ['grid', 'w-full', 'items-center', 'sticky', 'top-0', 'z-10'],
} as const;

export const DESKTOP_ROW_H = 60;
export const MOBILE_ROW_H = 96;
